config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'callPython' => 'static_pages#call'
  get 'runPython' => 'static_pages#run'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :photos

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeepFashion</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Montserrat:400,700' %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,800,900' %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,400,500,600,700' %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,400,600,700' %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
      	<% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
      	<% end %>
        <%= link_to "sample app", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <% if logged_in? %>
            	<li><%= link_to "Profile", current_user %></li>
            	<li><%= link_to "Log out", logout_path, method:"delete" %>
            <% else %>
		          <li><%= link_to "Log in", login_path %></li>
		          <li><%= link_to "Sign up", signup_path %></li>
		        <% end %>
          </ul>
        </nav>
      </div>
    </header> -->

<%= yield %>
<%= debug(params) if Rails.env.development? %>

</body>

</html>